# These are supported funding model platforms

custom: ['https://www.ersolucoesweb.com.br', 'https://youtube.com/UmaTagPorDia', 'https://facebook.com/everaldo.programador.fullstack', 'https://www.instagram.com/programador.fullstack/']
